# -*- coding: utf-8 -*-
"""
Created on Fri Apr 28 00:47:38 2017

@author: rlwar
"""

#Events
PLAYER_LEFT = 0
PLAYER_RIGHT = 1
PLAYER_STOP = 2
TALL_JUMP = 3
LONG_JUMP = 4
SHOOT = 5
PLAYER_TURN_END = 6

#Player directions
LEFT = 5
RIGHT = 6

#Player States
PLAYER_STATE_MOVE = 1
PLAYER_STATE_AIM = 2
PLAYER_STATE_ATTACK = 3
PLAYER_STATE_WAITING = 4
PLAYER_STATE_TURN_END = 5

#Game States
GS_PLAYER_MOVE = 0
GS_PLAYER_ATTACK = 1
GS_WAIT = 2
GS_MAIN_MENU = 3
GS_IN_GAME = 4
GS_GAME_OVER = 5